# General Jekyll Config
pygments: true
url: http://somethinglabs-blog.herokuapp.com
lsi: false
paginate: 5
paginate_path: ":num"
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, Procfile, vendor, gems]
permalink: :title

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#0071bc'
  show_disclaimer: true
